server:
  port: 8080

spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.15.4:1521:xe

    username: system
    password: devMaster19!
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.OracleDialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
